### ISSUE TITLE
'Class fileUploader does not exist' when bulk updating attributes for products

### ISSUE THREAD

**Issue by royvanos** [Yoast/Yoast-SEO-for-Magento2#56]
Hi Yoast/MaxServ team, when trying to to update attributes for multiple products we get a big error which means we can't so bulk product updates, you can reproduce this issue by going to **Catalog > Products**, selecting multiple products and then click on **Actions** and select **Update attributes**

Here's the error dump:
```1 exception(s):
Exception #0 (ReflectionException): Class fileUploader does not exist

Exception #0 (ReflectionException): Class fileUploader does not exist
#0 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('fileUploader')
#1 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('fileUploader')
#2 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('fileUploader')
#3 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('fileUploader', Array)
#4 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Data/Form/Element/Factory.php(81): Magento\Framework\ObjectManager\ObjectManager->create('fileUploader', Array)
#5 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Data/Form/AbstractForm.php(155): Magento\Framework\Data\Form\Element\Factory->create('fileUploader', Array)
#6 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Data/Form/Element/Fieldset.php(211): Magento\Framework\Data\Form\AbstractForm->addField('yoast_facebook_...', 'fileUploader', Array, false)
#7 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/module-backend/Block/Widget/Form.php(193): Magento\Framework\Data\Form\Element\Fieldset->addField('yoast_facebook_...', 'fileUploader', Array)
#8 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/module-catalog/Block/Adminhtml/Product/Edit/Action/Attribute/Tab/Attributes.php(93): Magento\Backend\Block\Widget\Form->_setFieldset(Array, Object(Magento\Framework\Data\Form\Element\Fieldset), Array)
#9 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/module-backend/Block/Widget/Form.php(141): Magento\Catalog\Block\Adminhtml\Product\Edit\Action\Attribute\Tab\Attributes->_prepareForm()
#10 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Element/AbstractBlock.php(658): Magento\Backend\Block\Widget\Form->_beforeToHtml()
#11 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/module-backend/Block/Widget/Tabs.php(387): Magento\Framework\View\Element\AbstractBlock->toHtml()
#12 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/module-backend/view/adminhtml/templates/widget/tabs.phtml(57): Magento\Backend\Block\Widget\Tabs->getTabContent(Object(Magento\Catalog\Block\Adminhtml\Product\Edit\Action\Attribute\Tab\Attributes))
#13 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/roy/Code/...')
#14 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Adminhtml\Product\Edit\Action\Attribute\Tabs), '/home/roy/Code/...', Array)
#15 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/roy/Code/...')
#16 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#17 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#18 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#19 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('attributes_tabs')
#20 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('attributes_tabs')
#21 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('attributes_tabs')
#22 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('attributes_tabs', false)
#23 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#24 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#25 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('attributes_tabs', false)
#26 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'attributes_tabs')
#27 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#28 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('attributes_tabs')
#29 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('left')
#30 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#31 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#32 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('left', false)
#33 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#34 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#35 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('left', false)
#36 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'left')
#37 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#38 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('left')
#39 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('side.col')
#40 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#41 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#42 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('side.col', false)
#43 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#44 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#45 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('side.col', false)
#46 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'side.col')
#47 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#48 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('side.col')
#49 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#50 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#51 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#52 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#53 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#54 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#55 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('page.main.conta...', false)
#56 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'page.main.conta...')
#57 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#58 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#59 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#60 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#61 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#62 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('page.content', false)
#63 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#64 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#65 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('page.content', false)
#66 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'page.content')
#67 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#68 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#69 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#70 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#71 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#72 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#73 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#74 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#75 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('page.wrapper', false)
#76 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'page.wrapper')
#77 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#78 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#79 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#80 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#81 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#82 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('backend.page', false)
#83 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#84 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#85 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('backend.page', false)
#86 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'backend.page')
#87 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#88 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#89 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#90 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#91 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#92 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Layout->renderElement('root', false)
#93 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Layout\Interceptor->___callParent('renderElement', Array)
#94 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderElement', Object(Magento\Framework\View\Layout\Interceptor), Array, 'hoTemplatehints...')
#95 /home/roy/Code/Magento/Shops/bodybow/app/code/Ho/Templatehints/Plugin/View/LayoutPlugin.php(77): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('root', false)
#96 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/Interception/Interceptor.php(142): Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'root')
#97 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(195): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderElement', Array, Array)
#98 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#99 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#100 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#101 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#102 /home/roy/Code/Magento/Shops/bodybow/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#103 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#104 /home/roy/Code/Magento/Shops/bodybow/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#105 /home/roy/Code/Magento/Shops/bodybow/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#106 {main}

**Comment by royvanos** [comment]
Nevermind, I see that this has been fixed with PR #53, issue can be closed.
